swagger: "2.0"
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: "1.0.0"
    termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /transaction:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction Module
            summary: List of all the bank accounts
            description: API for Transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string

            produces:
                - application/json
            responses:
                "200":
                    description: Bank Status List Fetch Successfully
                    schema:
                        $ref: "#/definitions/TransactionResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

    /transaction/{bankId}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction Module
            summary: List of all the transactions by bank
            description: API for Transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: bankId
                  description: The unique identifier of bank.
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transactions Fetch By Bank Successfully
                    schema:
                        $ref: "#/definitions/TransactionBankResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

    /transaction/item/{transactionId}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction Module
            summary: Transaction Information by ID
            description: API for Transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: transactionId
                  description: The unique identifier of transaction.
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transactions Fetch By Bank Successfully
                    schema:
                        $ref: "#/definitions/TransactionItem"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

        put:
            security:
                - Bearer: []
            tags:
                - Transaction Module
            summary: Transaction Informations Update
            description: API for Transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Token
                  required: true
                  type: string
                - in: path
                  name: transactionId
                  description: Transaction  ID.
                  required: true
                  type: string
                - in: body
                  name: updated info
                  description: An object of transaction information.
                  required: true
                  schema:
                      $ref: "#/definitions/TransactionModifiedItem"

            produces:
                - application/json
            responses:
                "201":
                    description: Transaction Supplementary Informations Update Fetch Successfully
                    schema:
                        $ref: "#/definitions/TransactionItem"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error

securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    Transaction:
        type: object
        properties:
            userId:
                type: number
    TransactionResponse:
        type: array
        items:
            $ref: "#/definitions/BankItem"
    BankItem:
        type: object
        properties:
            bankId:
                type: string
                description: Bank ID
            bankName:
                type: string
                description: Bank Name
            balance:
                type: number
                description: Balance in Bank
    TransactionBank:
        type: object
        properties:
            bankId:
                type: number
    TransactionBankResponse:
        type: array
        items:
            $ref: "#/definitions/TransactionItem"
    TransactionInfosId:
        type: object
        properties:
            transactionInfosId:
                type: number
    TransactionItem:
        type: object
        properties:
            transactionId:
                type: string
                description: Transaction ID
            date:
                type: string
                description: Transaction Date
            amount:
                type: string
                description: Transaction Amount
            description:
                type: string
                description: Transaction Description
            notes:
                type: string
                description: Transaction Notes
            category:
                type: string
                description: Transaction Category
                example: "Food"
            type:
                type: string
                description: Transaction Type
                example: "Electronic"

    TransactionModifiedItem:
        type: object
        properties:
            category:
                type: string
                description: Transaction Category
                example: "Food"
            note:
                type: string
                description: Transaction Note

    TransactionSupplementaryInfos:
        type: object
        properties:
            transactionInfosId:
                type: string
                description: Transaction Supplementary Infomations ID
            description:
                type: string
                description: Transaction Description
            category:
                type: string
                description: Transaction Category
                example: "Food"
            type:
                type: string
                description: Transaction Type
                example: "Electronic"
